change code according to Clean Code rules
luisgoncalves/xades4j pull request #281
Opened 2023-11-27 02:00 UTC by mjechow

I made some changes again. I think I finished this work now. What could be done

* There are some tests missing asserts. We could add AssertJ and use AssertDoesNotThrow in this cases. But I don't think thats worth it. 
* Sonar doesn't like it, when there are more than 5 parents. There are 6 or 7 from some classes.
* Some method are quite big and complex. Sonar suggests to simplify them.
* * public QualifyingProperty verify(
* * public void convertFromObjectTree(
* * void buildKeyInfo(
* * static KeyInfoRes process(
* * static ReferencesRes processReferences(
* the two ObjectFactory classes are really big, they should be split and 
* the constructors of SignerXXX have more than 10 parameter, we could introduce a builder pattern for them
* sonar suggests in private static class AllCertificatesSelector implements Selector<X509CertificateHolder>: A copy constructor, copy factory or a custom copy function are suitable alternatives to the Object.clone
* Optional should not by used in parameters

2023-11-27 02:26 UTC, mjechow commented on src/main/java/xades4j/production/DataObjectReference.java
>          uri = uri.trim();
we don't need this assignment anymore

2023-11-30 18:43 UTC, luisgoncalves requested changes
Thanks for the cleanup!
I've added a couple of comments that I think should be addressed.

2023-11-30 18:43 UTC, luisgoncalves commented on src/main/java/xades4j/production/DataObjectReference.java
>          uri = uri.trim();
Can you remove it, then?

2023-12-04 15:17 UTC, mjechow commented on src/main/java/xades4j/properties/IdentifierType.java
> -    OIDAsURN
Yeah your are right, that are the first braking changes so far. Probably I am a bit to harsh with this. Will change it.

2023-12-04 16:13 UTC, mjechow commented
Thanks for the comments. What do you think about the open tasks I mentioned. should I open some issues? I think the last three should be resolved, but there would be braking changes as well.

2023-12-05 19:49 UTC, luisgoncalves approved these changes
Thanks for the follow-up. I just noted one detail there in XmlQualifierType.

2023-12-05 19:49 UTC, luisgoncalves commented on src/main/java/xades4j/xml/bind/xades/XmlIntegerListType.java
It would be good to avoid future changes to types in xml/bind, because these were auto-generated. It's mostly noise in PRs. Perhaps it's possible to ignore these packages in the future.

2023-12-05 19:49 UTC, luisgoncalves commented on src/main/java/xades4j/xml/bind/xades/XmlQualifierType.java
I believe this change isn't needed.  This is generated code and the previous identifiers already used the proper naming convention.

The `ToXmlUtils` and `FromXmlUtils` can map to/from the two enum values in `IdentifierType` from the same value in this enum.

2023-12-05 20:09 UTC, luisgoncalves commented
Regarding the other open tasks, here are my thoughts:

> Some method are quite big and complex. Sonar suggests to simplify them.

Could be good to simplify a bit, but it's stable code, so really low prio and probably not worth it. 

> the two ObjectFactory classes are really big, they should be split and

It's auto-generated code. I'd say it shouldn't be changed, but instead ignored from analysis

> the constructors of SignerXXX have more than 10 parameter, we could introduce a builder pattern for them

There are instantiated via DI, so no caller would benefit from the builder. If anything, this may illustrate that responsibilities could be "grouped" somehow to avoid so many dependencies. Not sure.

> sonar suggests in private static class AllCertificatesSelector implements Selector<X509CertificateHolder>: A copy constructor, copy factory or a custom copy function are suitable alternatives to the Object.clone

The clone method comes from the implemented interface, plus it's a private class. IF you find a way to get rid of the warning, feel free to fix.

> Optional should not be used in parameters

This one comes from `SignerT`/`SignerC`, right? Those classes are package-private, so changes are not breaking. But they are instantiated by Guice (DI). I think Guice supports `@Nullable`, so the parameter could be nullable instead of Optional. feel free to fix.

2023-12-06 14:02 UTC, mjechow commented on src/main/java/xades4j/xml/bind/xades/XmlIntegerListType.java
yeah, I will exclude in the future.

2023-12-06 14:05 UTC, mjechow commented on src/main/java/xades4j/xml/bind/xades/XmlQualifierType.java
ok, got it. should I revert this change or is the code generated again?

2023-12-06 14:11 UTC, luisgoncalves commented on src/main/java/xades4j/xml/bind/xades/XmlQualifierType.java
It's not generated automatically. If you could revert that'd be great. I think everything else is good to merge.

2023-12-06 14:27 UTC, mjechow commented on src/main/java/xades4j/xml/bind/xades/XmlQualifierType.java
An update is on the way. But `pCnt += 1` is definitely wrong here, although it shouldn't change anything.

2023-12-06 14:32 UTC, mjechow commented
There is one more: 

ExclusiveCanonicalXMLParamsMarshaller.doMarshal() should return Collections.emptyList(); not Null. But this is a breaking change as well.

2023-12-06 14:44 UTC, mjechow commented
Unfortunately its not easily possible the change the Optional to @Nullable, because you have to bind a null explicitly. I don't know guice, so I don't resolve this issue.

2023-12-06 21:24 UTC, merged

2023-12-14 09:43 UTC, mjechow commented
Is there a chance of a new release containing this changes anytime soon?

2023-12-17 14:00 UTC, luisgoncalves commented
Yeah, I'll push one out soon.

2023-12-18 19:57 UTC, mjechow commented
Thanks for the release. I could already integrate it in my project. One remark for the release notes: it not "Guice to 6.0.0" but "Guice to 7.0.0".